apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name | default "kcsa-mock" }}-deployment
  labels:
    app: {{ .Values.labels.app | default "kcsa-mock" }}
    environment: {{ .Values.env.name }}
    {{- with .Values.labels.additional }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations.deployment }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app | default "kcsa-mock" }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app | default "kcsa-mock" }}
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccountName | default "default" }}
      imagePullSecrets:
        - name: gitlab-regcred
      containers:
        - name: kcsa-mock
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001  # Defina o UID numérico
            runAsGroup: 1001  # Defina o GID numérico
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: NODE_ENV
              value: {{ .Values.env.name }}
            {{- with .Values.env.variables }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "50m" }}
              memory: {{ .Values.resources.requests.memory | default "128Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "200m" }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}