apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kcsa-mock-network-policy
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.labels.app | default "kcsa-mock" }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.enabled }}
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.enabled }}
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
    {{- end }}