apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kcsa-mock-role
  namespace: {{ .Values.namespace.name }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]