apiVersion: v2
name: kcsa-mock
description: A simple helm chart to deploy csa on an openshift cluster 
version: 1.1.0
appVersion: "1.0"
maintainers:
  - name: Gabriel Carmo
    email: contato@gabrielandre.com.br